name: make-master

on:
    push:
        branches:
            - master
    schedule:
        - cron: "20 13 * * *"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
              with:
                  fetch-depth: 1
            - name: Run Makefile
              run: make lint
